# spec_cache.R — deterministic per-spec cache for multiverse + ablation
# =============================================================================
# Shared by multiverse.R (5.4) and l2_tier_leave_one_out.R (5.2/5.6).
#
# Root-cause fix for issues #6/#7: the pipeline IS deterministic given fixed
# input + config (verified: same code + same corrupted_enrichment.rds reruns
# produced identical ablation baselines). The apparent "drift" was stale
# result CSVs: the input rds (corrupted_enrichment.rds) is .gitignore'd and
# was regenerated by commit 2face4d (2 new catalog categories), after the
# multiverse/ablation CSVs had been produced with the old input. Re-running a
# benchmark with a changed input therefore changed every downstream number.
#
# Design: every spec execution is cached in validation/synthetic/spec_cache/
# keyed by sha256(input rds + package config + overrides). Rerunning a
# benchmark script with the same input + config reuses the cached summary, so
# the CSVs are stable. Changing the input (or config) invalidates the cache
# and forces a real re-execution, surfacing drift instead of hiding it.
#
# The cache stores a SMALL deterministic summary computed straight after the
# pipeline run -- NOT the raw corrected/review data -- so the cache stays
# light (one small .rds per spec).
#
#   summary fields:
#     label, mean_tst_h, mean_sol_min, mean_se_pct, analyzable_n, n_total,
#     n_error, n_unusual, n_flagged, cat_table (data.frame spec/cat/n),
#     flagged_injected, flagged_control

suppressPackageStartupMessages(library(digest))

SYN_DIR   <- "validation/synthetic"
CACHE_DIR <- file.path(SYN_DIR, "spec_cache")
CONFIG_RD <- "inst/config_default.yaml"
INPUT_RD  <- file.path(SYN_DIR, "corrupted_enrichment.rds")

sha256_file <- function(path) {
  if (!file.exists(path)) return("MISSING")
  digest::digest(file = path, algo = "sha256")
}

# Pipeline code fingerprint: hashes every R/ source file + every installed
# inst/scripts file. Guards against the #6/#7 "code drift" variant: a change
# to checkforerrors_processing.R (new guard) with unchanged input/config must
# invalidate cached summaries. Without this, the cache would serve stale
# results computed by the pre-change pipeline.
code_fingerprint <- function() {
  repo_r <- list.files("R", pattern = "\\.R$", full.names = TRUE)
  inst_s <- list.files("inst/scripts", pattern = "\\.R$", full.names = TRUE)
  sdir <- system.file("scripts", package = "splsleep")
  pkg_s <- if (nzchar(sdir)) list.files(sdir, pattern = "\\.R$", full.names = TRUE) else character()
  all_files <- unique(c(repo_r, inst_s, pkg_s))
  digest::digest(list(
    pkg_version = tryCatch(as.character(utils::packageVersion("splsleep")), error = function(e) "unknown"),
    files = lapply(all_files, sha256_file)
  ), algo = "sha256")
}

# Only overrides that differ from the bundled default count in the key, so
# multiverse "BASE" (all defaults) shares a cache slot with ablation
# "baseline" (empty overrides) -- one pipeline run, two clients.
norm_overrides <- function(overrides) {
  base_cfg <- yaml::read_yaml(CONFIG_RD)
  set_nested <- function(lst, keys, val) {
    if (length(keys) == 1) { lst[[keys]] <- val; return(lst) }
    lst[[keys[1]]] <- set_nested(lst[[keys[1]]], keys[-1], val); lst
  }
  base_val <- function(cfg, keys) {
    for (k in keys) { if (!is.list(cfg) || !k %in% names(cfg)) return(NULL); cfg <- cfg[[k]] }
    cfg
  }
  keep <- list()
  for (nm in names(overrides)) {
    keys <- strsplit(nm, ".", fixed = TRUE)[[1]]
    bv <- base_val(base_cfg, keys)
    # same value as default -> drop (default slot)
    if (!identical(bv, overrides[[nm]])) keep[[nm]] <- overrides[[nm]]
  }
  nm_sorted <- sort(names(keep))
  keep[nm_sorted]
}

spec_cache_key <- function(overrides, input_rds = INPUT_RD, extra_file = NULL) {
  digest::digest(list(
    input = sha256_file(input_rds),
    extra = if (is.null(extra_file)) NA else sha256_file(extra_file),
    cfg   = sha256_file(CONFIG_RD),
    code  = code_fingerprint(),
    ov    = norm_overrides(overrides)
  ), algo = "sha256")
}

cache_path <- function(label, overrides, input_rds = INPUT_RD, extra_file = NULL) {
  safe <- gsub("[^A-Za-z0-9_.-]", "_", label)
  file.path(CACHE_DIR, sprintf("%s_%s.rds", safe, spec_cache_key(overrides, input_rds, extra_file)))
}

save_spec_summary <- function(label, overrides, summary, input_rds = INPUT_RD, extra_file = NULL) {
  dir.create(CACHE_DIR, showWarnings = FALSE, recursive = TRUE)
  saveRDS(summary, cache_path(label, overrides, input_rds, extra_file))
  summary
}

load_spec_summary <- function(label, overrides, input_rds = INPUT_RD, extra_file = NULL) {
  p <- cache_path(label, overrides, input_rds, extra_file)
  if (file.exists(p)) {
    cat(sprintf("  [cache] %s (input+config unchanged)\n", label))
    readRDS(p)
  } else NULL
}

# Run the pipeline once for a set of overrides and collapse to the summary.
# Returns the cached summary if present. Never re-executes on cache hit.
# input_rds: benchmark input to run the pipeline on (defaults to the
# enrichment set; pass the real data rds for real-data spec curves).
# extra_file: optional supplementary CSV (StartDate/num_waso); enrichment
# sets have all columns inline so default NULL is correct. Real data
# requires the supplementary anon CSV named in config data.files.extra.
run_spec_once <- function(label, overrides, input_rds = INPUT_RD,
                          extra_file = NULL, verbose = TRUE) {
  hit <- load_spec_summary(label, overrides, input_rds, extra_file)
  if (!is.null(hit)) return(hit)

  cfg <- yaml::read_yaml(CONFIG_RD)
  set_nested <- function(lst, keys, val) {
    if (length(keys) == 1) { lst[[keys]] <- val; return(lst) }
    lst[[keys[1]]] <- set_nested(lst[[keys[1]]], keys[-1], val); lst
  }
  for (k in names(overrides)) {
    cfg <- set_nested(cfg, strsplit(k, ".", fixed = TRUE)[[1]], overrides[[k]])
  }

  # isolated run dir per spec to avoid cross-run state bleed
  run_dir <- file.path(tempdir(), paste0("spec_", substr(spec_cache_key(overrides, input_rds, extra_file), 1, 12)))
  dir.create(run_dir, showWarnings = FALSE, recursive = TRUE)
  file.copy(input_rds, file.path(run_dir, "main.rds"), overwrite = TRUE)
  cfg$data$files$main <- "main.rds"
  if (!is.null(extra_file)) {
    file.copy(extra_file, file.path(run_dir, "extra.csv"), overwrite = TRUE)
    cfg$data$files$extra <- "extra.csv"
  } else {
    cfg$data$files$extra <- NULL
  }
  yaml::write_yaml(cfg, file.path(run_dir, "config.yaml"))

  suppressPackageStartupMessages(library(splsleep))
  old_wd <- getwd()
  ok <- tryCatch({
    run_pipeline(config = "config.yaml", project_dir = run_dir,
                 skip_visualization = TRUE, verbose = FALSE)
    TRUE
  }, error = function(e) {
    cat("  SPEC ERROR:", label, "->", conditionMessage(e), "\n")
    FALSE
  }, finally = setwd(old_wd))
  if (!ok) return(NULL)

  corr <- get("corrected_ema_data", envir = .GlobalEnv)
  review <- get("review_output", envir = .GlobalEnv)
  d <- review$data_with_flags

  # flagged mask (needs_review_flag OR any _checkforerrors)
  flag_cols <- grep("_checkforerrors$", names(d), value = TRUE)
  fm <- rep(FALSE, nrow(d))
  for (c in flag_cols) fm <- fm | (d[[c]] %in% TRUE)
  flagged <- d$needs_review_flag %in% TRUE | fm

  gt <- read.csv(file.path(SYN_DIR, "ground_truth_enrichment.csv"), stringsAsFactors = FALSE)
  inj_ids <- gt$row_id[gt$error_type != "no_error_control"]
  ctrl_ids <- gt$row_id[gt$error_type == "no_error_control"]

  summary <- list(
    label = label,
    mean_tst_h   = mean(corr$self_diffcalc_totalsleeptime_minutes, na.rm = TRUE) / 60,
    mean_sol_min = mean(corr$self_diffcalc_sol_minutes, na.rm = TRUE),
    mean_se_pct  = mean(corr$self_diffcalc_sleepefficiency_percent, na.rm = TRUE),
    analyzable_n = sum(!is.na(corr$self_diffcalc_totalsleeptime_minutes)),
    n_total      = nrow(corr),
    n_error      = sum(corr$data_category == "error", na.rm = TRUE),
    n_unusual    = sum(corr$data_category == "unusual", na.rm = TRUE),
    n_flagged    = sum(corr$needs_review_flag %in% TRUE, na.rm = TRUE),
    cat_table    = as.data.frame(table(
      spec = rep(label, length(corr$data_category)),
      cat = corr$data_category, useNA = "no"), stringsAsFactors = FALSE),
    flagged_injected = sum(flagged[d$row_id %in% inj_ids]),
    flagged_control  = sum(flagged[d$row_id %in% ctrl_ids])
  )
  save_spec_summary(label, overrides, summary, input_rds, extra_file)
  summary
}