#!/usr/bin/env Rscript
# =============================================================================
# validation/reproduce_fasttrack_chain.R
#
# PURPOSE
#   One-command reproduction of the ENTIRE fasttrack human-review chain, from
#   the raw sber export to the user-facing review sheet. Every intermediate
#   file is regenerated by its own auditable script (each writes a
#   provenance sidecar), so "how did manual_disambiguation_fasttrack.csv get
#   these 23 rows?" has a scripted, re-runnable answer.
#
# CHAIN (each step is idempotent and writes *.provenance.json):
#   1. derive_timegap_candidates.R
#        sber_ema_anon_20260227.csv -> timegap_candidates_3to6h.csv (46 rows)
#   2. disambiguate_timegap_candidates.R
#        timegap_candidates_3to6h.csv + manual_error/unusual_corrections.csv
#        -> disambiguation_worksheet_tiered_fasttrack.csv (23 rows)
#        -> disambiguation_worksheet_tiered_fullreview_{cyra,maia}.csv (3)
#   3. promote_fasttrack_for_review.R
#        disambiguation_worksheet_tiered_fasttrack.csv
#        -> manual_disambiguation_fasttrack.csv (pure copy + sidecar)
#   4. rebuild_fasttrack_complete.R  (zero-join)
#        manual_disambiguation_fasttrack.csv
#        -> manual_disambiguation_fasttrack.csv (Time_* cols completed)
#        -> fasttrack_review.csv (user-facing sheet)
#
# USAGE
#   Rscript validation/reproduce_fasttrack_chain.R [--keep-snapshots]
#   Default: backs up pre-existing fasttrack_review.csv +
#   manual_disambiguation_fasttrack.csv to validation/_snapshots/ before
#   overwriting, then runs the chain.
# =============================================================================

args <- commandArgs(trailingOnly = TRUE)
keep_snapshots <- "--keep-snapshots" %in% args

snap_dir <- "validation/_snapshots"
dir.create(snap_dir, showWarnings = FALSE, recursive = TRUE)

# Pre-existing review outputs are curated (Accept/Notes may be filled in).
# Snapshot them so a chain re-run never silently destroys human judgments.
for (f in c("fasttrack_review.csv", "manual_disambiguation_fasttrack.csv")) {
  if (file.exists(f)) {
    snap <- file.path(snap_dir, sprintf("%s_prechain_%s.csv",
      tools::file_path_sans_ext(f), format(Sys.time(), "%Y%m%d_%H%M%S")))
    file.copy(f, snap, overwrite = TRUE)
    cat("Snapshot:", snap, "\n")
  }
}

run_step <- function(label, cmd) {
  cat(sprintf("\n=== [%s] %s ===\n", label, cmd))
  status <- system2("Rscript", strsplit(cmd, " ")[[1]])
  if (status != 0) {
    stop(sprintf("Step failed (exit %d): %s", status, cmd))
  }
  cat(sprintf("=== [%s] OK ===\n", label))
}

run_step("1/4 derive candidates",   "validation/derive_timegap_candidates.R")
run_step("2/4 disambiguate",        "validation/disambiguate_timegap_candidates.R")
run_step("3/4 promote fasttrack",   "validation/promote_fasttrack_for_review.R")
run_step("4/4 rebuild (zero-join)", "validation/rebuild_fasttrack_complete.R")

cat("\n=== CHAIN COMPLETE ===\n")
cat("Outputs:\n")
cat("  timegap_candidates_3to6h.csv                 (46 rows)\n")
cat("  disambiguation_worksheet_tiered_fasttrack.csv (23 rows)\n")
cat("  manual_disambiguation_fasttrack.csv           (23 rows, Time_* completed)\n")
cat("  fasttrack_review.csv                          (user-facing)\n")
cat("Provenance sidecars: *.provenance.json next to each CSV\n")

# Final integrity check: the review sheet must agree with the worksheet
ws <- read.csv("disambiguation_worksheet_tiered_fasttrack.csv", stringsAsFactors = FALSE, check.names = FALSE)
rv <- read.csv("fasttrack_review.csv", stringsAsFactors = FALSE, check.names = FALSE)
stopifnot(nrow(ws) == nrow(rv))
stopifnot(identical(as.character(ws$pid), as.character(rv$PID)))
stopifnot(identical(as.character(ws$raw_row_id), as.character(rv$Row_ID)))
cat("\nIntegrity: review sheet row count and pid/row_id order match worksheet.\n")
cat("Chain is reproducible: re-running this script regenerates all files.\n")